/**
 *
 * Copyright (c) 2013, Linagora
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA 
 *
 */
package org.ow2.play.governance.permission.api;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebService;

import org.ow2.play.governance.api.GovernanceExeption;
import org.ow2.play.metadata.api.MetaResource;

/**
 * @author chamerling
 * 
 */
@WebService
public interface PermissionService {

	/**
	 * 
	 * @return
	 * @throws GovernanceExeption
	 */
	@WebMethod
	List<MetaResource> getPermissions() throws GovernanceExeption;

	/**
	 * 
	 * @return
	 * @throws GovernanceExeption
	 */
	@WebMethod
	MetaResource getPermission(String name) throws GovernanceExeption;

	/**
	 * 
	 * @param meta
	 * @throws GovernanceExeption
	 */
	@WebMethod
	void add(MetaResource meta) throws GovernanceExeption;
	
	/**
	 * 
	 * @param permission
	 * @return the permission ID. generated by the service if not set as input.
	 * 
	 * @throws GovernanceExeption
	 */
	@WebMethod
	String addPermission(Permission permission) throws GovernanceExeption;
	
	/**
	 * Change the modes. Will override teh current ones
	 * 
	 * @param name
	 * @param modes
	 * @throws GovernanceExeption
	 */
	@WebMethod
	void setMode(String name, List<String> modes) throws GovernanceExeption;
	
	/**
	 * 
	 * @param name
	 * @param accessTo
	 * @throws GovernanceExeption
	 */
	@WebMethod
	void setAccessTo(String name, List<String> accessTo) throws GovernanceExeption;
	
	/**
	 * 
	 * @param name
	 * @param accessTo
	 * @throws GovernanceExeption
	 */
	@WebMethod
	void setAgent(String name, List<String> agents) throws GovernanceExeption;

	/**
	 * 
	 * @param name
	 * @throws GovernanceExeption
	 */
	@WebMethod
	void remove(String name) throws GovernanceExeption;

}
